### PR TITLE
validate round 2

### PR DESCRIPTION
**Pull request by shadowlion**

### CODE REVIEW

**Comment by HeyAri** [comment]
If you leave all fields unmarked:
In Safari, it prompts for certificate but not other fields. On hitting ok in the dialog box, reCaptcha pops up instead of returning to the form.

In Chrome, hitting the submit button will not prompt for required fields.

Sounds like a little change to the jQuery to check fields in order, and maybe webkits are needed?

Your thoughts?

**Comment by shadowlion** [comment]
My approach at this point would be to just validate via jquery everywhere, rather than using the html validations. You would be able to customize the error messages to your liking as well.

All the Best,

Justin Chiou
chiou.kai@gmail.com
630-204-8122
justinchiou.me

**Comment by shadowlion** [comment]
I’m not getting the same errors as you on Safari - without filling it out, if I keep pressing the submit button, it will eventually focus me towards the top of the form telling me I need to input something.

I see what you mean about the chrome browser, though - probably need to see if everything’s validated FIRST, then check the certificate. The reason why this one validation is so wonky is because I hid the radio buttons underneath, so the first issue was that it was trying to focus a hidden input. 

All the Best,

Justin Chiou
chiou.kai@gmail.com
630-204-8122
justinchiou.me

**Comment by HeyAri** [comment]
Is there a script for that, or do we need to build a waterfall to manage it?

**Comment by shadowlion** [comment]
Try this <http://formvalidation.io/>

All the Best,

Justin Chiou
chiou.kai@gmail.com
630-204-8122
justinchiou.me

**Comment by HeyAri** [comment]
I’d almost rather revert to a simpler version of validation. While it is looking good as capabilities in programming for your portfolio, It is out of my capability set for my portfolio. That might be ok as I’m looking for UX/UI design jobs, but it is beyond my skills to program or support it. What do you think about where we are with it?

**Comment by shadowlion** [comment]
UX/UI jobs usually demand only html/css/php, so it’s understandable if you don’t wanna add any more js components - if that’s the case, you’ll have to forego the reCAPTCHA capability, as that’s the one that’s really breaking it.

If you can work on cleaning up any assets you don’t need, it should be pretty good after that. I suppose when applying for jobs and whatnot, you gotta ask yourself what the intentions of your works in your portfolio are - is this site mainly to show off your php skills? or Front end? or Functionality? or both? Normally, a well-rounded front-end developer would be versed in javascript, so I’d start by learning this as a priority.

Trust me when I say it’s NOT beyond your skills to support it. You’re doing fine; just google search more.

All the Best,

Justin Chiou
chiou.kai@gmail.com
630-204-8122
justinchiou.me

**Comment by HeyAri** [comment]
That jQuery thing you sent is $50, too much for just a toy website. Let's see if the recaptcha actually helps. So far I'm still seeing fake certs come through. Then we can decide whether to reset to an earlier version or blaze ahead with a different validation.

**Comment by shadowlion** [comment]
if bots are becoming a problem, you might wanna try porting over to Heroku, and point the DNS servers to use your regular url.

**Pull request merged**
